//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  post: Post;
  postConnection: PostConnection;
  service: Service;
  serviceConnection: ServiceConnection;
  project: Project;
  projectConnection: ProjectConnection;
  agent: Agent;
  agentConnection: AgentConnection;
  schoolModule: SchoolModule;
  schoolModuleConnection: SchoolModuleConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
};


export type QueryServiceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
};


export type QueryProjectArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
};


export type QueryAgentArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAgentConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AgentFilter>;
};


export type QuerySchoolModuleArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySchoolModuleConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SchoolModuleFilter>;
};

export type DocumentFilter = {
  post?: InputMaybe<PostFilter>;
  service?: InputMaybe<ServiceFilter>;
  project?: InputMaybe<ProjectFilter>;
  agent?: InputMaybe<AgentFilter>;
  schoolModule?: InputMaybe<SchoolModuleFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Post | Service | Project | Agent | SchoolModule | Folder;

export type PostSeo = {
  __typename?: 'PostSeo';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  keywords?: Maybe<Scalars['String']['output']>;
  ogImage?: Maybe<Scalars['String']['output']>;
};

export type PostKnowledgeGraphNodes = {
  __typename?: 'PostKnowledgeGraphNodes';
  id?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
};

export type PostKnowledgeGraphEdges = {
  __typename?: 'PostKnowledgeGraphEdges';
  from?: Maybe<Scalars['String']['output']>;
  to?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type PostKnowledgeGraph = {
  __typename?: 'PostKnowledgeGraph';
  nodes?: Maybe<Array<Maybe<PostKnowledgeGraphNodes>>>;
  edges?: Maybe<Array<Maybe<PostKnowledgeGraphEdges>>>;
};

export type PostProtocolEval = {
  __typename?: 'PostProtocolEval';
  protocol?: Maybe<Scalars['String']['output']>;
  chain?: Maybe<Scalars['String']['output']>;
  tvl?: Maybe<Scalars['String']['output']>;
  riskScore?: Maybe<Scalars['String']['output']>;
  audit?: Maybe<Scalars['String']['output']>;
  recommendation?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  auditedBy?: Maybe<Scalars['String']['output']>;
  launchDate?: Maybe<Scalars['String']['output']>;
};

export type Post = Node & Document & {
  __typename?: 'Post';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  excerpt?: Maybe<Scalars['String']['output']>;
  access?: Maybe<Scalars['String']['output']>;
  status?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  seo?: Maybe<PostSeo>;
  knowledgeGraph?: Maybe<PostKnowledgeGraph>;
  protocolEval?: Maybe<PostProtocolEval>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PostSeoFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
  ogImage?: InputMaybe<StringFilter>;
};

export type PostKnowledgeGraphNodesFilter = {
  id?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
};

export type PostKnowledgeGraphEdgesFilter = {
  from?: InputMaybe<StringFilter>;
  to?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type PostKnowledgeGraphFilter = {
  nodes?: InputMaybe<PostKnowledgeGraphNodesFilter>;
  edges?: InputMaybe<PostKnowledgeGraphEdgesFilter>;
};

export type PostProtocolEvalFilter = {
  protocol?: InputMaybe<StringFilter>;
  chain?: InputMaybe<StringFilter>;
  tvl?: InputMaybe<StringFilter>;
  riskScore?: InputMaybe<StringFilter>;
  audit?: InputMaybe<StringFilter>;
  recommendation?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  auditedBy?: InputMaybe<StringFilter>;
  launchDate?: InputMaybe<StringFilter>;
};

export type PostFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  excerpt?: InputMaybe<StringFilter>;
  access?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  seo?: InputMaybe<PostSeoFilter>;
  knowledgeGraph?: InputMaybe<PostKnowledgeGraphFilter>;
  protocolEval?: InputMaybe<PostProtocolEvalFilter>;
};

export type PostConnectionEdges = {
  __typename?: 'PostConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Post>;
};

export type PostConnection = Connection & {
  __typename?: 'PostConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostConnectionEdges>>>;
};

export type Service = Node & Document & {
  __typename?: 'Service';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  duration?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServiceFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
};

export type ServiceConnectionEdges = {
  __typename?: 'ServiceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Service>;
};

export type ServiceConnection = Connection & {
  __typename?: 'ServiceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServiceConnectionEdges>>>;
};

export type Project = Node & Document & {
  __typename?: 'Project';
  title: Scalars['String']['output'];
  type?: Maybe<Scalars['String']['output']>;
  detail?: Maybe<Scalars['String']['output']>;
  status?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProjectFilter = {
  title?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  detail?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
};

export type ProjectConnectionEdges = {
  __typename?: 'ProjectConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Project>;
};

export type ProjectConnection = Connection & {
  __typename?: 'ProjectConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectConnectionEdges>>>;
};

export type Agent = Node & Document & {
  __typename?: 'Agent';
  title: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
  status?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AgentFilter = {
  title?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type AgentConnectionEdges = {
  __typename?: 'AgentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Agent>;
};

export type AgentConnection = Connection & {
  __typename?: 'AgentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AgentConnectionEdges>>>;
};

export type SchoolModule = Node & Document & {
  __typename?: 'SchoolModule';
  title: Scalars['String']['output'];
  duration?: Maybe<Scalars['String']['output']>;
  free?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SchoolModuleFilter = {
  title?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  free?: InputMaybe<BooleanFilter>;
};

export type SchoolModuleConnectionEdges = {
  __typename?: 'SchoolModuleConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SchoolModule>;
};

export type SchoolModuleConnection = Connection & {
  __typename?: 'SchoolModuleConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SchoolModuleConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePost: Post;
  createPost: Post;
  updateService: Service;
  createService: Service;
  updateProject: Project;
  createProject: Project;
  updateAgent: Agent;
  createAgent: Agent;
  updateSchoolModule: SchoolModule;
  createSchoolModule: SchoolModule;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationCreatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationUpdateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationCreateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationUpdateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationCreateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationUpdateAgentArgs = {
  relativePath: Scalars['String']['input'];
  params: AgentMutation;
};


export type MutationCreateAgentArgs = {
  relativePath: Scalars['String']['input'];
  params: AgentMutation;
};


export type MutationUpdateSchoolModuleArgs = {
  relativePath: Scalars['String']['input'];
  params: SchoolModuleMutation;
};


export type MutationCreateSchoolModuleArgs = {
  relativePath: Scalars['String']['input'];
  params: SchoolModuleMutation;
};

export type DocumentUpdateMutation = {
  post?: InputMaybe<PostMutation>;
  service?: InputMaybe<ServiceMutation>;
  project?: InputMaybe<ProjectMutation>;
  agent?: InputMaybe<AgentMutation>;
  schoolModule?: InputMaybe<SchoolModuleMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  post?: InputMaybe<PostMutation>;
  service?: InputMaybe<ServiceMutation>;
  project?: InputMaybe<ProjectMutation>;
  agent?: InputMaybe<AgentMutation>;
  schoolModule?: InputMaybe<SchoolModuleMutation>;
};

export type PostSeoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  keywords?: InputMaybe<Scalars['String']['input']>;
  ogImage?: InputMaybe<Scalars['String']['input']>;
};

export type PostKnowledgeGraphNodesMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
};

export type PostKnowledgeGraphEdgesMutation = {
  from?: InputMaybe<Scalars['String']['input']>;
  to?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type PostKnowledgeGraphMutation = {
  nodes?: InputMaybe<Array<InputMaybe<PostKnowledgeGraphNodesMutation>>>;
  edges?: InputMaybe<Array<InputMaybe<PostKnowledgeGraphEdgesMutation>>>;
};

export type PostProtocolEvalMutation = {
  protocol?: InputMaybe<Scalars['String']['input']>;
  chain?: InputMaybe<Scalars['String']['input']>;
  tvl?: InputMaybe<Scalars['String']['input']>;
  riskScore?: InputMaybe<Scalars['String']['input']>;
  audit?: InputMaybe<Scalars['String']['input']>;
  recommendation?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  auditedBy?: InputMaybe<Scalars['String']['input']>;
  launchDate?: InputMaybe<Scalars['String']['input']>;
};

export type PostMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  access?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  seo?: InputMaybe<PostSeoMutation>;
  knowledgeGraph?: InputMaybe<PostKnowledgeGraphMutation>;
  protocolEval?: InputMaybe<PostProtocolEvalMutation>;
};

export type ServiceMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  detail?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
};

export type AgentMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SchoolModuleMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  free?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PostPartsFragment = { __typename: 'Post', title: string, slug: string, category?: string | null, author?: string | null, date?: string | null, excerpt?: string | null, access?: string | null, status?: string | null, body?: any | null, seo?: { __typename: 'PostSeo', title?: string | null, description?: string | null, keywords?: string | null, ogImage?: string | null } | null, knowledgeGraph?: { __typename: 'PostKnowledgeGraph', nodes?: Array<{ __typename: 'PostKnowledgeGraphNodes', id?: string | null, label?: string | null, type?: string | null } | null> | null, edges?: Array<{ __typename: 'PostKnowledgeGraphEdges', from?: string | null, to?: string | null, label?: string | null } | null> | null } | null, protocolEval?: { __typename: 'PostProtocolEval', protocol?: string | null, chain?: string | null, tvl?: string | null, riskScore?: string | null, audit?: string | null, recommendation?: string | null, category?: string | null, auditedBy?: string | null, launchDate?: string | null } | null };

export type ServicePartsFragment = { __typename: 'Service', title: string, description?: string | null, price?: string | null, duration?: string | null };

export type ProjectPartsFragment = { __typename: 'Project', title: string, type?: string | null, detail?: string | null, status?: string | null };

export type AgentPartsFragment = { __typename: 'Agent', title: string, role?: string | null, status?: string | null, description?: string | null };

export type SchoolModulePartsFragment = { __typename: 'SchoolModule', title: string, duration?: string | null, free?: boolean | null };

export type PostQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PostQuery = { __typename?: 'Query', post: { __typename: 'Post', id: string, title: string, slug: string, category?: string | null, author?: string | null, date?: string | null, excerpt?: string | null, access?: string | null, status?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'PostSeo', title?: string | null, description?: string | null, keywords?: string | null, ogImage?: string | null } | null, knowledgeGraph?: { __typename: 'PostKnowledgeGraph', nodes?: Array<{ __typename: 'PostKnowledgeGraphNodes', id?: string | null, label?: string | null, type?: string | null } | null> | null, edges?: Array<{ __typename: 'PostKnowledgeGraphEdges', from?: string | null, to?: string | null, label?: string | null } | null> | null } | null, protocolEval?: { __typename: 'PostProtocolEval', protocol?: string | null, chain?: string | null, tvl?: string | null, riskScore?: string | null, audit?: string | null, recommendation?: string | null, category?: string | null, auditedBy?: string | null, launchDate?: string | null } | null } };

export type PostConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
}>;


export type PostConnectionQuery = { __typename?: 'Query', postConnection: { __typename?: 'PostConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostConnectionEdges', cursor: string, node?: { __typename: 'Post', id: string, title: string, slug: string, category?: string | null, author?: string | null, date?: string | null, excerpt?: string | null, access?: string | null, status?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'PostSeo', title?: string | null, description?: string | null, keywords?: string | null, ogImage?: string | null } | null, knowledgeGraph?: { __typename: 'PostKnowledgeGraph', nodes?: Array<{ __typename: 'PostKnowledgeGraphNodes', id?: string | null, label?: string | null, type?: string | null } | null> | null, edges?: Array<{ __typename: 'PostKnowledgeGraphEdges', from?: string | null, to?: string | null, label?: string | null } | null> | null } | null, protocolEval?: { __typename: 'PostProtocolEval', protocol?: string | null, chain?: string | null, tvl?: string | null, riskScore?: string | null, audit?: string | null, recommendation?: string | null, category?: string | null, auditedBy?: string | null, launchDate?: string | null } | null } | null } | null> | null } };

export type ServiceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServiceQuery = { __typename?: 'Query', service: { __typename: 'Service', id: string, title: string, description?: string | null, price?: string | null, duration?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ServiceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
}>;


export type ServiceConnectionQuery = { __typename?: 'Query', serviceConnection: { __typename?: 'ServiceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServiceConnectionEdges', cursor: string, node?: { __typename: 'Service', id: string, title: string, description?: string | null, price?: string | null, duration?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ProjectQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectQuery = { __typename?: 'Query', project: { __typename: 'Project', id: string, title: string, type?: string | null, detail?: string | null, status?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProjectConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
}>;


export type ProjectConnectionQuery = { __typename?: 'Query', projectConnection: { __typename?: 'ProjectConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectConnectionEdges', cursor: string, node?: { __typename: 'Project', id: string, title: string, type?: string | null, detail?: string | null, status?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AgentQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AgentQuery = { __typename?: 'Query', agent: { __typename: 'Agent', id: string, title: string, role?: string | null, status?: string | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AgentConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AgentFilter>;
}>;


export type AgentConnectionQuery = { __typename?: 'Query', agentConnection: { __typename?: 'AgentConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AgentConnectionEdges', cursor: string, node?: { __typename: 'Agent', id: string, title: string, role?: string | null, status?: string | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SchoolModuleQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SchoolModuleQuery = { __typename?: 'Query', schoolModule: { __typename: 'SchoolModule', id: string, title: string, duration?: string | null, free?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SchoolModuleConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SchoolModuleFilter>;
}>;


export type SchoolModuleConnectionQuery = { __typename?: 'Query', schoolModuleConnection: { __typename?: 'SchoolModuleConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SchoolModuleConnectionEdges', cursor: string, node?: { __typename: 'SchoolModule', id: string, title: string, duration?: string | null, free?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PostPartsFragmentDoc = gql`
    fragment PostParts on Post {
  __typename
  title
  slug
  category
  author
  date
  excerpt
  access
  status
  body
  seo {
    __typename
    title
    description
    keywords
    ogImage
  }
  knowledgeGraph {
    __typename
    nodes {
      __typename
      id
      label
      type
    }
    edges {
      __typename
      from
      to
      label
    }
  }
  protocolEval {
    __typename
    protocol
    chain
    tvl
    riskScore
    audit
    recommendation
    category
    auditedBy
    launchDate
  }
}
    `;
export const ServicePartsFragmentDoc = gql`
    fragment ServiceParts on Service {
  __typename
  title
  description
  price
  duration
}
    `;
export const ProjectPartsFragmentDoc = gql`
    fragment ProjectParts on Project {
  __typename
  title
  type
  detail
  status
}
    `;
export const AgentPartsFragmentDoc = gql`
    fragment AgentParts on Agent {
  __typename
  title
  role
  status
  description
}
    `;
export const SchoolModulePartsFragmentDoc = gql`
    fragment SchoolModuleParts on SchoolModule {
  __typename
  title
  duration
  free
}
    `;
export const PostDocument = gql`
    query post($relativePath: String!) {
  post(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostParts
  }
}
    ${PostPartsFragmentDoc}`;
export const PostConnectionDocument = gql`
    query postConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostFilter) {
  postConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostParts
      }
    }
  }
}
    ${PostPartsFragmentDoc}`;
export const ServiceDocument = gql`
    query service($relativePath: String!) {
  service(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServiceParts
  }
}
    ${ServicePartsFragmentDoc}`;
export const ServiceConnectionDocument = gql`
    query serviceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServiceFilter) {
  serviceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServiceParts
      }
    }
  }
}
    ${ServicePartsFragmentDoc}`;
export const ProjectDocument = gql`
    query project($relativePath: String!) {
  project(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectParts
  }
}
    ${ProjectPartsFragmentDoc}`;
export const ProjectConnectionDocument = gql`
    query projectConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectFilter) {
  projectConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectParts
      }
    }
  }
}
    ${ProjectPartsFragmentDoc}`;
export const AgentDocument = gql`
    query agent($relativePath: String!) {
  agent(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AgentParts
  }
}
    ${AgentPartsFragmentDoc}`;
export const AgentConnectionDocument = gql`
    query agentConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AgentFilter) {
  agentConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AgentParts
      }
    }
  }
}
    ${AgentPartsFragmentDoc}`;
export const SchoolModuleDocument = gql`
    query schoolModule($relativePath: String!) {
  schoolModule(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SchoolModuleParts
  }
}
    ${SchoolModulePartsFragmentDoc}`;
export const SchoolModuleConnectionDocument = gql`
    query schoolModuleConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SchoolModuleFilter) {
  schoolModuleConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SchoolModuleParts
      }
    }
  }
}
    ${SchoolModulePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      post(variables: PostQueryVariables, options?: C): Promise<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}> {
        return requester<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}, PostQueryVariables>(PostDocument, variables, options);
      },
    postConnection(variables?: PostConnectionQueryVariables, options?: C): Promise<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}> {
        return requester<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}, PostConnectionQueryVariables>(PostConnectionDocument, variables, options);
      },
    service(variables: ServiceQueryVariables, options?: C): Promise<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}> {
        return requester<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}, ServiceQueryVariables>(ServiceDocument, variables, options);
      },
    serviceConnection(variables?: ServiceConnectionQueryVariables, options?: C): Promise<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}> {
        return requester<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}, ServiceConnectionQueryVariables>(ServiceConnectionDocument, variables, options);
      },
    project(variables: ProjectQueryVariables, options?: C): Promise<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}> {
        return requester<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}, ProjectQueryVariables>(ProjectDocument, variables, options);
      },
    projectConnection(variables?: ProjectConnectionQueryVariables, options?: C): Promise<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}, ProjectConnectionQueryVariables>(ProjectConnectionDocument, variables, options);
      },
    agent(variables: AgentQueryVariables, options?: C): Promise<{data: AgentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgentQueryVariables, query: string}> {
        return requester<{data: AgentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgentQueryVariables, query: string}, AgentQueryVariables>(AgentDocument, variables, options);
      },
    agentConnection(variables?: AgentConnectionQueryVariables, options?: C): Promise<{data: AgentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgentConnectionQueryVariables, query: string}> {
        return requester<{data: AgentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgentConnectionQueryVariables, query: string}, AgentConnectionQueryVariables>(AgentConnectionDocument, variables, options);
      },
    schoolModule(variables: SchoolModuleQueryVariables, options?: C): Promise<{data: SchoolModuleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SchoolModuleQueryVariables, query: string}> {
        return requester<{data: SchoolModuleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SchoolModuleQueryVariables, query: string}, SchoolModuleQueryVariables>(SchoolModuleDocument, variables, options);
      },
    schoolModuleConnection(variables?: SchoolModuleConnectionQueryVariables, options?: C): Promise<{data: SchoolModuleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SchoolModuleConnectionQueryVariables, query: string}> {
        return requester<{data: SchoolModuleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SchoolModuleConnectionQueryVariables, query: string}, SchoolModuleConnectionQueryVariables>(SchoolModuleConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  