/**
 * SUPERCOMPUTE — Pages Functions middleware (runs in front of every Function).
 * ===========================================================================
 *
 * PURPOSE (card t_58f99396, follow-up F5 to SupercomputeA/Master_Main#59)
 * ----------------------------------------------------------------------
 * Cloudflare does not apply `public/_headers` to responses generated by Pages
 * Functions. `public/_headers` stays the source of truth for static assets; the
 * header list for FUNCTION responses lives in exactly one place —
 * `functions/_shared/security-headers.js` — and this middleware is its only
 * consumer. If the two ever disagree, the middleware wins for `/api/*`.
 *
 * WHAT IT DOES
 * ------------
 *   const response = await context.next();   // the route handler runs
 *   return withSecurityHeaders(response);    // nosniff, referrer-policy, COOP,
 *                                            // permissions-policy, + CSP on docs
 *
 * It never rewrites a body, a status code, or a CORS header. Responses are
 * cloned (a Function response is immutable) and only the security header names
 * are set, so `Access-Control-Allow-Origin` and friends survive untouched.
 *
 * ERROR PATH
 * ----------
 * An exception thrown by a route would otherwise be rendered by Pages' own
 * error handler — an HTML page with no `nosniff`, no CSP and no access-control
 * headers, which is precisely the surface this card exists to close ("it
 * becomes real the moment a Function returns HTML, an error page, or a
 * reflected body"). So the exception is logged and converted into a 500 with a
 * non-renderable body: JSON for `/api/*` (matching what every other error in
 * these Functions returns) and `text/plain` otherwise. The status code is
 * unchanged at 500; the original error is never reflected into the body.
 *
 * SCOPE OF THIS MIDDLEWARE — `/api/*` only
 * ----------------------------------------
 * The decoration is applied to the Functions surface (`/api/*`) and nothing
 * else: every request outside `/api/*` is handed straight back with
 * `context.next()`, untouched. Two reasons, both deliberate:
 *
 *  1. `public/_headers` is the source of truth for STATIC assets. A root
 *     `_middleware.js` that rewrote every response would silently become the
 *     de-facto authority for static assets too, and could overwrite a
 *     path-specific `_headers` rule added later.
 *  2. It keeps the static path byte-identical — no response cloning/stream
 *     relay on `_next/static/**`.
 *
 * Every Pages Function in this project lives under `functions/api/`. When one
 * is added outside `/api/`, widen `FUNCTION_PATH_PREFIX` here — do not add a
 * second middleware.
 *
 * NOT A ROUTE
 * -----------
 * This file is `_middleware.js`, so Pages treats it as middleware and not as an
 * endpoint. `functions/_shared/security-headers.js` exports no `onRequest`
 * handler, so it is bundled as a helper and never exposed as a route (verified:
 * `/_shared/security-headers.js` 404s).
 *
 * ROUTING NOTE (disclosed, not discovered later): a root `_middleware.js` is
 * documented by Cloudflare as running in front of static files as well, so the
 * deployment's function-invocation profile changes — static requests can now
 * invoke the Worker. Restoring the pre-change profile (Functions invoked for
 * `/api/*` only) is a `public/_routes.json` include/exclude decision on its own
 * card: it can break routing and must not ride along with a header change.
 */

import { withSecurityHeaders } from "./_shared/security-headers.js";

const FUNCTION_PATH_PREFIX = "/api/";

export async function onRequest(context) {
  const isFunctionRoute = new URL(context.request.url).pathname.startsWith(
    FUNCTION_PATH_PREFIX,
  );
  if (!isFunctionRoute) {
    // Static asset / SPA route: `_headers` owns this response. Do not touch it.
    return context.next();
  }

  try {
    return withSecurityHeaders(await context.next());
  } catch (error) {
    const detail = error instanceof Error ? `${error.message}\n${error.stack}` : String(error);
    console.error(`[security-headers] unhandled function error: ${detail}`);
    return withSecurityHeaders(internalErrorResponse(context.request));
  }
}

function internalErrorResponse(request) {
  const isApi = new URL(request.url).pathname.startsWith("/api/");
  const wantsJson =
    isApi || (request.headers.get("Accept") || "").toLowerCase().includes("application/json");

  return wantsJson
    ? new Response(JSON.stringify({ error: "Internal error" }), {
        status: 500,
        headers: { "Content-Type": "application/json; charset=utf-8" },
      })
    : new Response("Internal error", {
        status: 500,
        headers: { "Content-Type": "text/plain; charset=utf-8" },
      });
}
