/**
 * SUPERCOMPUTE — security header set for Pages Functions responses.
 * =================================================================
 *
 * WHY THIS FILE EXISTS
 * --------------------
 * Cloudflare does NOT apply `public/_headers` to responses generated by Pages
 * Functions ("Custom headers defined in the _headers file are not applied to
 * responses generated by Pages Functions, even if the request URL matches a
 * rule defined in _headers"). This project ships `functions/`, so before this
 * module every `/api/*` response went out with no `X-Content-Type-Options`, no
 * `Referrer-Policy`, no `Cross-Origin-Opener-Policy` and no CSP — while the
 * static pages got all of them. Verified live on 2026-09-11:
 *   curl -sI https://supercompute.io/api/school  -> none of the above
 *   curl -sI https://supercompute.io/terms      -> all of the above
 * This is the Cloudflare static-asset path vs the Functions path, not a config
 * mistake.
 *
 * WHERE THE HEADER LIST LIVES
 * ---------------------------
 * This module is the single place the FUNCTIONS header list is defined, and it
 * is the only thing `functions/_middleware.js` reads. `public/_headers` remains
 * the source of truth for STATIC assets; the `/*` block there and the constants
 * below are kept identical on purpose. If the two ever disagree, THIS module
 * wins for `/api/*` (it runs last, on the response the Function already built).
 *
 * WHO THIS PROTECTS / WHO IT DOES NOT
 * -----------------------------------
 * The middleware that imports this sits in front of the Functions router, so it
 * decorates what a Function returns (including its own error responses). It does
 * NOT decorate a platform error page — an exception that escapes the Worker is
 * rendered by Pages' own error path. `functions/_middleware.js` therefore
 * catches thrown errors and answers with a non-renderable body so there is no
 * un-decorated HTML error surface under /api/*.
 *
 * WHAT IS DELIBERATELY NOT HERE
 * -----------------------------
 * `Cross-Origin-Embedder-Policy: require-corp` is declared in `public/_headers`
 * on main but was never applied (missing path section). The CSP pull request
 * (SupercomputeA/Master_Main#59) removes it rather than newly enabling it,
 * because `require-corp` blocks every cross-origin image/media that lacks a CORP
 * header. This module follows that decision: COOP `same-origin` is kept (no
 * render impact), COEP is not set.
 *
 * Drift note: when the `/*` block of `public/_headers` changes, mirror the value
 * here in the same pull request. Do not add per-route header sets in
 * `functions/` — add them here so there is exactly one list.
 */

/**
 * The `/*` security header block of `public/_headers`, as of
 * SupercomputeA/Master_Main#59 (security/csp-headers). Applied to EVERY response
 * that leaves a Pages Function.
 */
export const SECURITY_HEADERS = Object.freeze({
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Cross-Origin-Opener-Policy": "same-origin",
  "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
});

/**
 * The document policy from `public/_headers` (Master_Main#59). Applied ONLY to
 * responses that are actually documents — see `isDocumentResponse()`.
 */
export const CONTENT_SECURITY_POLICY =
  "default-src 'self'; " +
  "script-src 'self'; " +
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; " +
  "img-src 'self' data: https:; " +
  "font-src 'self' data: https://fonts.gstatic.com; " +
  "connect-src 'self' https://api.neynar.com https://fonts.gstatic.com " +
  "https://mainnet.base.org https://eth.llamarpc.com " +
  "https://ethereum-rpc.publicnode.com https://cloudflare-eth.com " +
  "https://*.walletconnect.com https://*.walletconnect.org " +
  "wss://*.walletconnect.com wss://*.walletconnect.org; " +
  "media-src 'self' blob: https:; " +
  "worker-src 'self' blob:; " +
  "frame-src 'self' https://*.walletconnect.com https://*.walletconnect.org " +
  "https://www.youtube.com https://calendly.com; " +
  "object-src 'none'; " +
  "base-uri 'self'; " +
  "form-action 'self'; " +
  "frame-ancestors 'self'; " +
  "upgrade-insecure-requests";

/** Statuses that must not carry a body — cloning one with `res.body` throws. */
const NULL_BODY_STATUS = new Set([101, 103, 204, 205, 304]);

/**
 * DECISION (explicit, per card t_58f99396): the CSP directive is attached only
 * when the response actually carries a renderable document.
 *
 * - No body at all (`Content-Length: 0` / null stream — e.g. the `OPTIONS`
 *   preflight that every `/api/*` route answers with `new Response(null, …)`)
 *   -> NO CSP. Found on the live local run: keying on `Content-Type` alone put a
 *   700-byte document policy on every preflight, which is pure payload noise.
 * - `text/html` / `application/xhtml+xml` -> yes, it is a document, CSP applies.
 * - Has a body but no `Content-Type` at all -> yes, fail safe (a body with no
 *   declared type is exactly the sniffing case, and `nosniff` is set beside it).
 * - `application/json`, `text/plain`, binary, everything else -> NO CSP.
 *   A CSP on a JSON body is inert (the body is never parsed as a document, and
 *   `nosniff` forbids type-sniffing it into one), so attaching the policy to
 *   every `/api/*` response would be pure payload cost. Every route under
 *   `functions/` returned JSON when this was written.
 *
 * If a Function ever starts returning HTML (or an error page), it is covered
 * automatically — that is the point of keying on the response, not the path.
 */
export function isDocumentResponse(response) {
  if (response.body === null) return false;
  const contentType = (response.headers.get("Content-Type") || "").toLowerCase();
  if (contentType === "") return true;
  return contentType.includes("text/html") || contentType.includes("application/xhtml+xml");
}

/**
 * Returns a NEW Response carrying the security header set.
 *
 * A Pages Function response is immutable, so the response is cloned with
 * `new Response(body, response)`. Every header the route already set is
 * preserved verbatim — this is what keeps the per-route CORS headers intact
 * (`functions/api/auth.js`, `school.js`, `farcaster.js`, `token.js`,
 * `web3/[[catchall]].js` each set their own `Access-Control-Allow-Origin`).
 * Only the header names in SECURITY_HEADERS / CSP are touched.
 *
 * A route-supplied CSP is respected (it can only be narrower than the default),
 * which is why the CSP is set with `if (!headers.has(...))`.
 */
export function withSecurityHeaders(response) {
  const body = NULL_BODY_STATUS.has(response.status) ? null : response.body;
  const cloned = new Response(body, {
    status: response.status,
    statusText: response.statusText,
    headers: new Headers(response.headers),
  });

  for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
    cloned.headers.set(name, value);
  }
  if (isDocumentResponse(cloned) && !cloned.headers.has("Content-Security-Policy")) {
    cloned.headers.set("Content-Security-Policy", CONTENT_SECURITY_POLICY);
  }

  return cloned;
}
