#!/usr/bin/env node
// scripts/seed-kg-data.mjs
//
// Hydrate the kg_nodes + kg_edges tables in D1 from /public/data/kg/*.json.
// This is the SAME JSON the API falls back to when D1 is unavailable, so
// the static and D1 paths render the same data.
//
// Idempotency: INSERT OR REPLACE on PRIMARY KEY (kg_nodes.id) lets this
// run against an existing D1 without producing duplicates; edges are
// cleared per graph and re-inserted to keep the relation set in sync.
//
// Usage:
//   # Generate SQL to pipe into wrangler:
//   node scripts/seed-kg-data.mjs > /tmp/kg-seed.sql
//   npx wrangler d1 execute supercompute-db --remote --file=/tmp/kg-seed.sql
//
//   # Local (Cloudflare D1 local emulation via wrangler):
//   node scripts/seed-kg-data.mjs --local | npx wrangler d1 execute supercompute-db --local --file=-

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '..')
const dataDir = resolve(repoRoot, 'public', 'data', 'kg')

const GRAPHS = ['school', 'police', 'defi', 'articles']

function escape(str) {
  if (str == null) return ''
  return String(str).replace(/'/g, "''")
}

function edgeToSql(graph, e) {
  // Static fallback files store edges as either [source, target] or
  // { source, target, label? }. Normalize before writing to D1.
  if (Array.isArray(e)) {
    const [source, target, label] = e
    return `INSERT INTO kg_edges (graph, source, target, label) VALUES ('${escape(graph)}', '${escape(source)}', '${escape(target)}', '${escape(label ?? '')}');`
  }
  return `INSERT INTO kg_edges (graph, source, target, label) VALUES ('${escape(graph)}', '${escape(e.source)}', '${escape(e.target)}', '${escape(e.label ?? '')}');`
}

const out = []
out.push('-- Generated by scripts/seed-kg-data.mjs — do not edit by hand.')
out.push('-- Re-running is idempotent: INSERT OR REPLACE on kg_nodes,')
out.push('-- edges cleared per graph + re-inserted.')
out.push('')

for (const graph of GRAPHS) {
  const path = resolve(dataDir, `${graph}.json`)
  const raw = readFileSync(path, 'utf8')
  const data = JSON.parse(raw)
  out.push(`-- ─── ${graph} ───`)
  for (const n of data.nodes) {
    const cols = ['id', 'graph', 'label', 'type', 'description', 'level', 'x', 'y', 'r', 'metadata']
    const metadata = n.metadata ?? (n.slug || n.date || n.datetime || n.num != null || n.role || n.stance || n.author || n.up != null
      ? JSON.stringify({
          ...(n.slug ? { slug: n.slug } : {}),
          ...(n.date ? { date: n.date } : {}),
          ...(n.datetime ? { datetime: n.datetime } : {}),
          ...(n.num != null ? { num: n.num } : {}),
          ...(n.role ? { role: n.role } : {}),
          ...(n.stance ? { stance: n.stance } : {}),
          ...(n.author ? { author: n.author } : {}),
          ...(n.up != null ? { up: n.up } : {}),
        })
      : '{}')
    const vals = [
      escape(n.id),
      escape(graph),
      escape(n.label),
      escape(n.type),
      escape(n.description ?? ''),
      escape(n.level ?? ''),
      Number.isFinite(n.x) ? n.x : 0.5,
      Number.isFinite(n.y) ? n.y : 0.5,
      Number.isFinite(n.r) ? n.r : 0.05,
      escape(metadata),
    ]
    const levelSql = vals[5] ? `'${vals[5]}'` : 'NULL'
    out.push(
      `INSERT OR REPLACE INTO kg_nodes (${cols.join(', ')}) VALUES ('${vals[0]}', '${vals[1]}', '${vals[2]}', '${vals[3]}', '${vals[4]}', ${levelSql}, ${vals[6]}, ${vals[7]}, ${vals[8]}, '${vals[9]}');`
    )
  }
  out.push(`DELETE FROM kg_edges WHERE graph = '${escape(graph)}';`)
  for (const e of data.edges) {
    out.push(edgeToSql(graph, e))
  }
  out.push('')
}

out.push('-- Seed complete.')
process.stdout.write(out.join('\n'))
